/*
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Plan;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Redemption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-11T14:10:28.965Z")



public class Redemption {
  @SerializedName("id")
  private String id = null;

  @SerializedName("plan")
  private Plan plan = null;

  @SerializedName("requestRaisedOn")
  private OffsetDateTime requestRaisedOn = null;

  @SerializedName("requestProcessedOn")
  private OffsetDateTime requestProcessedOn = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    RAISED("raised"),
    
    PROCESSING("processing"),
    
    SUCCESSFUL("successful"),
    
    FAILED("failed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

   /**
   * Unique identifier for the redemption request
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier for the redemption request")
  public String getId() {
    return id;
  }

  public Redemption plan(Plan plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  @ApiModelProperty(value = "")
  public Plan getPlan() {
    return plan;
  }

  public void setPlan(Plan plan) {
    this.plan = plan;
  }

   /**
   * Get requestRaisedOn
   * @return requestRaisedOn
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRequestRaisedOn() {
    return requestRaisedOn;
  }

   /**
   * Get requestProcessedOn
   * @return requestProcessedOn
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRequestProcessedOn() {
    return requestProcessedOn;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Redemption redemption = (Redemption) o;
    return Objects.equals(this.id, redemption.id) &&
        Objects.equals(this.plan, redemption.plan) &&
        Objects.equals(this.requestRaisedOn, redemption.requestRaisedOn) &&
        Objects.equals(this.requestProcessedOn, redemption.requestProcessedOn) &&
        Objects.equals(this.status, redemption.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, plan, requestRaisedOn, requestProcessedOn, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Redemption {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    requestRaisedOn: ").append(toIndentedString(requestRaisedOn)).append("\n");
    sb.append("    requestProcessedOn: ").append(toIndentedString(requestProcessedOn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

