/*
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SchemeRedemptionOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-11T14:10:28.965Z")



public class SchemeRedemptionOption {
  @SerializedName("startMonth")
  private Integer startMonth = null;

  @SerializedName("startDate")
  private Integer startDate = null;

  public SchemeRedemptionOption startMonth(Integer startMonth) {
    this.startMonth = startMonth;
    return this;
  }

   /**
   * month after which the redemption can be applied
   * @return startMonth
  **/
  @ApiModelProperty(value = "month after which the redemption can be applied")
  public Integer getStartMonth() {
    return startMonth;
  }

  public void setStartMonth(Integer startMonth) {
    this.startMonth = startMonth;
  }

  public SchemeRedemptionOption startDate(Integer startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * date in the above month after which the redemption can be applied
   * @return startDate
  **/
  @ApiModelProperty(value = "date in the above month after which the redemption can be applied")
  public Integer getStartDate() {
    return startDate;
  }

  public void setStartDate(Integer startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemeRedemptionOption schemeRedemptionOption = (SchemeRedemptionOption) o;
    return Objects.equals(this.startMonth, schemeRedemptionOption.startMonth) &&
        Objects.equals(this.startDate, schemeRedemptionOption.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startMonth, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemeRedemptionOption {\n");
    
    sb.append("    startMonth: ").append(toIndentedString(startMonth)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

