/*
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Cancellation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CancellationApi
 */
@Ignore
public class CancellationApiTest {

    private final CancellationApi api = new CancellationApi();

    
    /**
     * Create a new cancellation request for a plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addCancellationTest() throws ApiException {
        Cancellation body = null;
        api.addCancellation(body);

        // TODO: test validations
    }
    
    /**
     * Edit a cancellation request for a plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editCancellationTest() throws ApiException {
        String cancellationId = null;
        Cancellation body = null;
        api.editCancellation(cancellationId, body);

        // TODO: test validations
    }
    
    /**
     * Fetch all cancellations
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchAllCancellationsTest() throws ApiException {
        List<Cancellation> response = api.fetchAllCancellations();

        // TODO: test validations
    }
    
    /**
     * Get cancellation by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCancellationTest() throws ApiException {
        String cancellationId = null;
        Cancellation response = api.getCancellation(cancellationId);

        // TODO: test validations
    }
    
}
