/*
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Plan;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlanApi
 */
@Ignore
public class PlanApiTest {

    private final PlanApi api = new PlanApi();

    
    /**
     * Add a new plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPlanTest() throws ApiException {
        Plan body = null;
        api.addPlan(body);

        // TODO: test validations
    }
    
    /**
     * Edit a plan&#39;s details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editPlanTest() throws ApiException {
        String planId = null;
        Plan body = null;
        api.editPlan(planId, body);

        // TODO: test validations
    }
    
    /**
     * Fetch all plans
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchAllPlansTest() throws ApiException {
        List<Plan> response = api.fetchAllPlans();

        // TODO: test validations
    }
    
    /**
     * Get a plan by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlanTest() throws ApiException {
        String planId = null;
        Plan response = api.getPlan(planId);

        // TODO: test validations
    }
    
}
