/*
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Product;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductApi
 */
@Ignore
public class ProductApiTest {

    private final ProductApi api = new ProductApi();

    
    /**
     * Add a new product
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addProductTest() throws ApiException {
        Product body = null;
        Product response = api.addProduct(body);

        // TODO: test validations
    }
    
    /**
     * Edit product details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editProductTest() throws ApiException {
        String productId = null;
        Product body = null;
        api.editProduct(productId, body);

        // TODO: test validations
    }
    
    /**
     * Fetch all products
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchAllProductsTest() throws ApiException {
        List<Product> response = api.fetchAllProducts();

        // TODO: test validations
    }
    
    /**
     * Get product by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductTest() throws ApiException {
        String productId = null;
        Product response = api.getProduct(productId);

        // TODO: test validations
    }
    
}
