/*
 * Tortoise Merchant API
 * Tortoise API for merchant to integrate with their existing systems 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@tortoise.pro
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Redemption;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RedemptionApi
 */
@Ignore
public class RedemptionApiTest {

    private final RedemptionApi api = new RedemptionApi();

    
    /**
     * Create a new redemption request for a plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addRedemptionTest() throws ApiException {
        Redemption body = null;
        api.addRedemption(body);

        // TODO: test validations
    }
    
    /**
     * Edit a redemption request for a plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editRedemptionTest() throws ApiException {
        String redemptionId = null;
        Redemption body = null;
        api.editRedemption(redemptionId, body);

        // TODO: test validations
    }
    
    /**
     * Fetch all redemption requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fetchAllRedemptionsTest() throws ApiException {
        List<Redemption> response = api.fetchAllRedemptions();

        // TODO: test validations
    }
    
    /**
     * Get a redemption request by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRedemptionTest() throws ApiException {
        String redemptionId = null;
        Redemption response = api.getRedemption(redemptionId);

        // TODO: test validations
    }
    
}
